{
    "name": "<?php echo $this->items['namepkg']?>",
    "description": "component",
    "type": "library",
    "license": "BSD-3-Clause",
    "keywords": [
        "core",
        "adteam"
    ],
    "require": {
        "php": "^5.6 || ^7.0"
    },   
    "autoload": {
        "psr-4": {
            "Adteam\\<?php echo $this->items['namespace']?>\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Adteam\\<?php echo $this->items['namespace']?>\\": "src/"
        }
    }
}
