<?php echo '<?php';?>

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

namespace <?php echo $this->items['namespace']?>;

use Zend\ServiceManager\ServiceManager;
use Doctrine\ORM\EntityManager;

/**
 * Description of Command
 *
 * @author dev
 */
 
class Repository
{
    
    /**
     *
     * @var type 
     */
    protected $services;

    /**
     * 
     * @param ServiceManager $services
     */
    public function __construct(ServiceManager $services)
    {
        $this->services = $services;
    }
}

