<?php echo '<?php';?>

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

namespace <?php echo $this->items['namespace']?>;

use Zend\Console\Adapter\AdapterInterface;
use ZF\Console\Route;

/**
 * Description of Command
 *
 * @author dev
 */
 
class Command
{
    
    protected $console;
    
    protected $route;
    
    public function __invoke(Route $route, AdapterInterface $console)
    {
        $this->console = $console;
        $this->route = $route;
        $param1 = $route->getMatchedParam('param1');
        $param2 = $route->getMatchedParam('param2');
        $this->console->write("Param 1; {$param1}... \n"); 
        $this->console->write("Param 2; {$param2}... \n");
    }
}

